trigger:
  - codecov

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - task: Npm@1
    displayName: 'Install CheckPoint dependencies'
    inputs:
      verbose: false
      command: install
      
  - script: |
      set -e
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      disown -ar
    displayName: 'Start xvfb'
    condition: eq(variables['Agent.OS'], 'Linux')
    
  - task: Npm@1
    displayName: 'Run unit tests via npm script'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run test-coverage'
    env:
      DISPLAY: ":99.0"
      
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: 'out-cov/*-results.xml'
      testRunTitle: '$(Agent.OS)-Tests'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish Code Coverage'
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: coverage/cobertura-coverage.xml
      reportDirectory: coverage/lcov-report
      pathToSources: $(System.DefaultWorkingDirectory)
    condition: succeededOrFailed()
  
  - bash: |
      bash <(curl https://codecov.io/bash) -t $TOKEN -f coverage/cobertura-coverage.xml
    displayName: 'codecov'
    condition: succeededOrFailed()
    env:
      TOKEN: $(CODECOV_TOKEN)
      
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/coverage'
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy coverage output'

  - task: PublishPipelineArtifact@0
    displayName: 'Publish Coverage Artifact'
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifactName: 'coverage-$(Agent.OS)'